#!/bin/bash

# This script exports YouTube cookies from a local browser and uploads them to a remote server

# Default values
BROWSER="chrome"
LOCAL_COOKIES_FILE="/tmp/www.youtube.com_cookies.txt"
REMOTE_USER=""
REMOTE_HOST=""
REMOTE_PATH=""
RESTART_SERVICE=false

# Display help message
function show_help {
    echo "Usage: $0 [options]"
    echo "Export YouTube cookies from a local browser and upload them to a remote server"
    echo ""
    echo "Options:"
    echo "  -b, --browser BROWSER   Browser to export cookies from (chrome, firefox, safari, edge, opera)"
    echo "  -l, --local FILE        Local file to save cookies to (default: $LOCAL_COOKIES_FILE)"
    echo "  -u, --user USER         Remote username"
    echo "  -h, --host HOST         Remote hostname or IP address"
    echo "  -p, --path PATH         Remote directory path to upload cookies to (e.g., ~/nosvid)"
    echo "  -r, --restart           Restart the NosVid service on the remote server"
    echo "  --help                  Show this help message"
    echo ""
    echo "Example:"
    echo "  $0 -b chrome -u kim -h videos.bitcoinops.de -p ~/nosvid -r"
    echo ""
    echo "This will upload the cookies file to: kim@videos.bitcoinops.de:~/nosvid/www.youtube.com_cookies.txt"
    echo "Note: The tilde (~) will be expanded on the remote server."
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -b|--browser)
            BROWSER="$2"
            shift 2
            ;;
        -l|--local)
            LOCAL_COOKIES_FILE="$2"
            shift 2
            ;;
        -u|--user)
            REMOTE_USER="$2"
            shift 2
            ;;
        -h|--host)
            REMOTE_HOST="$2"
            shift 2
            ;;
        -p|--path)
            REMOTE_PATH="$2"
            shift 2
            ;;
        -r|--restart)
            RESTART_SERVICE=true
            shift
            ;;
        --help)
            show_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Check required parameters
if [ -z "$REMOTE_USER" ] || [ -z "$REMOTE_HOST" ] || [ -z "$REMOTE_PATH" ]; then
    echo "Error: Remote user, host, and path are required"
    show_help
    exit 1
fi

# Check if browser_cookie3 is installed
if ! python3 -c "import browser_cookie3" &>/dev/null; then
    echo "Installing browser_cookie3..."
    pip3 install browser_cookie3
fi

# Create a temporary Python script to export cookies
TEMP_SCRIPT=$(mktemp)
cat > "$TEMP_SCRIPT" << 'EOF'
#!/usr/bin/env python3
import sys
import browser_cookie3

def export_cookies(browser, domain, output_file):
    try:
        # Get cookies from browser
        if browser == 'chrome':
            cj = browser_cookie3.chrome(domain_name=domain)
        elif browser == 'firefox':
            cj = browser_cookie3.firefox(domain_name=domain)
        elif browser == 'safari':
            cj = browser_cookie3.safari(domain_name=domain)
        elif browser == 'edge':
            cj = browser_cookie3.edge(domain_name=domain)
        elif browser == 'opera':
            cj = browser_cookie3.opera(domain_name=domain)
        else:
            print(f"Unsupported browser: {browser}")
            return False

        # Save cookies to file in Netscape format
        with open(output_file, 'w') as f:
            # Write the Netscape cookies file header
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# https://curl.haxx.se/docs/http-cookies.html\n")
            f.write("# This file was generated by upload_youtube_cookies.sh\n\n")

            for cookie in cj:
                # Handle None expires value
                expires = "0" if cookie.expires is None else str(int(cookie.expires))
                secure_flag = "TRUE" if cookie.secure else "FALSE"
                http_only_flag = "TRUE" if getattr(cookie, 'has_nonstandard_attr', False) and cookie.has_nonstandard_attr('HttpOnly') else "FALSE"

                # Format: domain, flag, path, secure, expires, name, value
                f.write(f"{cookie.domain}\t")
                f.write(f"{'TRUE' if cookie.domain.startswith('.') else 'FALSE'}\t")
                f.write(f"{cookie.path}\t")
                f.write(f"{secure_flag}\t")
                f.write(f"{expires}\t")
                f.write(f"{cookie.name}\t")
                f.write(f"{cookie.value}\n")

        # Count cookies
        cookie_count = len(cj)
        if cookie_count == 0:
            print(f"No cookies found for {domain} in {browser}")
            return False

        print(f"Exported {cookie_count} cookies for {domain} from {browser} to {output_file}")
        return True

    except Exception as e:
        print(f"Error exporting cookies: {e}")
        return False

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python script.py BROWSER DOMAIN OUTPUT_FILE")
        sys.exit(1)

    browser = sys.argv[1]
    domain = sys.argv[2]
    output_file = sys.argv[3]

    success = export_cookies(browser, domain, output_file)
    sys.exit(0 if success else 1)
EOF

# Make the script executable
chmod +x "$TEMP_SCRIPT"

# Export cookies
echo "Exporting YouTube cookies from $BROWSER..."
if ! python3 "$TEMP_SCRIPT" "$BROWSER" "youtube.com" "$LOCAL_COOKIES_FILE"; then
    echo "Failed to export cookies"
    rm "$TEMP_SCRIPT"
    exit 1
fi

# Upload cookies to the remote server
# Set the remote destination path
REMOTE_DEST="$REMOTE_PATH/www.youtube.com_cookies.txt"

# Print and execute the exact SCP command
SCP_COMMAND="scp $LOCAL_COOKIES_FILE $REMOTE_USER@$REMOTE_HOST:$REMOTE_DEST"
echo "Executing: $SCP_COMMAND"

# Execute the command and check for errors in one step
if ! eval "$SCP_COMMAND"; then
    echo "Failed to upload cookies"
    rm "$TEMP_SCRIPT"
    exit 1
fi

# Restart the NosVid service if requested
if [ "$RESTART_SERVICE" = true ]; then
    echo "Restarting NosVid service on $REMOTE_HOST..."
    if ! ssh "$REMOTE_USER@$REMOTE_HOST" "sudo systemctl restart nosvid.service"; then
        echo "Failed to restart NosVid service"
        rm "$TEMP_SCRIPT"
        exit 1
    fi

    echo "NosVid service restarted successfully"
fi

# Clean up
rm "$TEMP_SCRIPT"

echo "YouTube cookies uploaded successfully to $REMOTE_USER@$REMOTE_HOST:$REMOTE_DEST!"
echo ""
echo "If you need to update your config.yaml on the remote server, run:"
echo "ssh $REMOTE_USER@$REMOTE_HOST \"echo 'youtube:' >> ~/nosvid/config.yaml\""
echo "ssh $REMOTE_USER@$REMOTE_HOST \"echo '  cookies_file: $REMOTE_DEST' >> ~/nosvid/config.yaml\""
